"""Remove the scene floor and mark collision guides in standard H2 output."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from pxr import Gf, Usd, UsdGeom, UsdPhysics


def finalize(package: Path) -> None:
    """Remove the scene floor and mark collision guides."""
    stage = Usd.Stage.Open(str(package / "H2Loop.usda"))
    root = stage.GetDefaultPrim()
    floor = root.GetPath().AppendPath("Geometry/floor")
    geometry = Usd.Stage.Open(str(package / "Payload/Geometry.usda"))
    physics = Usd.Stage.Open(str(package / "Payload/Physics.usda"))
    materials = Usd.Stage.Open(str(package / "Payload/Materials.usda"))
    for layer_stage in (geometry, physics, materials):
        layer_stage.RemovePrim(floor)

    for prim in stage.Traverse():
        if prim.HasAPI(UsdPhysics.CollisionAPI) and UsdGeom.Imageable(prim):
            imageable = UsdGeom.Imageable(geometry.GetPrimAtPath(prim.GetPath()))
            imageable.CreatePurposeAttr(UsdGeom.Tokens.guide)

    for layer_stage in (geometry, physics, materials):
        layer_stage.GetRootLayer().Save()
    # Refresh the converter's cached bounds after removing the scene floor.
    bounds = (
        UsdGeom.BBoxCache(
            Usd.TimeCode.Default(), [UsdGeom.Tokens.default_, UsdGeom.Tokens.guide]
        )
        .ComputeWorldBound(root)
        .ComputeAlignedBox()
    )
    root.GetAttribute("extentsHint").Set(
        [Gf.Vec3f(bounds.GetMin()), Gf.Vec3f(bounds.GetMax())]
    )
    stage.GetRootLayer().Save()
    files = {
        path.relative_to(package).as_posix(): hashlib.sha256(
            path.read_bytes()
        ).hexdigest()
        for path in sorted(package.rglob("*"))
        if path.is_file() and path.name != "BUILD.json"
    }
    (package / "BUILD.json").write_text(json.dumps({"files": files}, indent=2) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "package", type=Path, help="Directory generated by mujoco_usd_converter"
    )
    finalize(parser.parse_args().package.resolve())
