"""Apply three H2 compatibility adjustments to standard converter output."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from pxr import Gf, Usd, UsdGeom, UsdPhysics


def finalize(package: Path) -> None:
    """Remove the scene floor, mark collision guides, and preserve effort limits."""
    stage = Usd.Stage.Open(str(package / "H2Loop.usda"))
    root = stage.GetDefaultPrim()
    floor = root.GetPath().AppendPath("Geometry/floor")
    geometry = Usd.Stage.Open(str(package / "Payload/Geometry.usda"))
    physics = Usd.Stage.Open(str(package / "Payload/Physics.usda"))
    materials = Usd.Stage.Open(str(package / "Payload/Materials.usda"))
    for layer_stage in (geometry, physics, materials):
        layer_stage.RemovePrim(floor)

    for prim in stage.Traverse():
        if prim.HasAPI(UsdPhysics.CollisionAPI) and UsdGeom.Imageable(prim):
            imageable = UsdGeom.Imageable(geometry.GetPrimAtPath(prim.GetPath()))
            imageable.CreatePurposeAttr(UsdGeom.Tokens.guide)
        if not (
            prim.IsA(UsdPhysics.RevoluteJoint) or prim.IsA(UsdPhysics.PrismaticJoint)
        ):
            continue
        lower = prim.GetAttribute("mjc:actuatorfrcrange:min").Get()
        upper = prim.GetAttribute("mjc:actuatorfrcrange:max").Get()
        limited = prim.GetAttribute("mjc:actuatorfrclimited").Get()
        if limited == "false" or lower is None or upper is None or lower >= upper:
            continue
        if lower != -upper:
            raise ValueError(
                f"Cannot preserve asymmetric effort range on {prim.GetPath()}"
            )
        drive_name = "linear" if prim.IsA(UsdPhysics.PrismaticJoint) else "angular"
        drive = UsdPhysics.DriveAPI.Apply(
            physics.GetPrimAtPath(prim.GetPath()), drive_name
        )
        drive.CreateTypeAttr(UsdPhysics.Tokens.force)
        drive.CreateStiffnessAttr(0.0)
        drive.CreateDampingAttr(0.0)
        drive.CreateMaxForceAttr(upper)

    for layer_stage in (geometry, physics, materials):
        layer_stage.GetRootLayer().Save()
    # Refresh the converter's cached bounds after removing the scene floor.
    bounds = (
        UsdGeom.BBoxCache(
            Usd.TimeCode.Default(), [UsdGeom.Tokens.default_, UsdGeom.Tokens.guide]
        )
        .ComputeWorldBound(root)
        .ComputeAlignedBox()
    )
    root.GetAttribute("extentsHint").Set(
        [Gf.Vec3f(bounds.GetMin()), Gf.Vec3f(bounds.GetMax())]
    )
    stage.GetRootLayer().Save()
    files = {
        path.relative_to(package).as_posix(): hashlib.sha256(
            path.read_bytes()
        ).hexdigest()
        for path in sorted(package.rglob("*"))
        if path.is_file() and path.name != "BUILD.json"
    }
    (package / "BUILD.json").write_text(json.dumps({"files": files}, indent=2) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "package", type=Path, help="Directory generated by mujoco_usd_converter"
    )
    finalize(parser.parse_args().package.resolve())
